require: 
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 20
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false